import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const quicksand = Quicksand({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning className='relative'>
      <body className={quicksand.className}>
        <div className='flex text-xs items-center gap-4 fixed bottom-0 left-0 right-0 bg-zinc-100'>
          <Link href='/'>Home</Link>
          <Link href='/dashboard'>Dashboard</Link>
          <Link href='/sign-in'>SignIn</Link>
          <Link href='/sign-up'>SignUp</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
